# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    binfmt.emulatedSystems = [
      "aarch64-linux"
    ];
    loader = {
      systemd-boot.enable = lib.mkForce false;
      efi.canTouchEfiVariables = true;
      efi.efiSysMountPoint = "/boot";
    };
    lanzaboote.enable = true;
    lanzaboote.pkiBundle = "/var/lib/sbctl";
    supportedFilesystems = {
      exfat = true;
    };

    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usb_storage"
      "usbhid"
      "sd_mod"
      "rtsx_pci_sdmmc"
      "aesni_intel"
    ];
    initrd.kernelModules = [ "dm-snapshot" ];
    initrd.luks.devices."cryptroot" = {
      device = "/dev/nvme0n1p2";
      bypassWorkqueues = true;
      allowDiscards = true;
    };
    kernelModules = [
      "kvm-amd"
      "cryptd"
    ];
    kernelPackages = pkgs.linuxPackages_zen;
    extraModulePackages = [ ];
    extraModprobeConfig = "";
    # options rtw89_core disable_ps_mode=y
    # options rtw89_pci disable_aspm=y
    kernelParams = [
      "8250.nr_uarts=0" # disable legacy COM ports (-load time)
      "pcie_aspm=off"
    ];
    resumeDevice = "/dev/nixos/swap";
    blacklistedKernelModules = [ "ideapad_laptop" ];
  };

  swapDevices = [ { device = "/dev/nixos/swap"; } ];

  fileSystems."/" = {
    device = "/dev/nixos/root";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/46B3-B5C5";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
      "nofail"
    ];
  };

  # fileSystems."/mnt/windows" = {
  #   device = "/dev/disk/by-uuid/9EFC0CCBFC0CA01F";
  #   fsType = "ntfs";
  #   options = [
  #     "defaults"
  #     "nofail"
  #     "dmask=027"
  #     "fmask=027"
  #     "uid=1000"
  #     "gid=1000"
  #   ];
  # };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    enableAllFirmware = true;

    amdgpu = {
      initrd.enable = true;
    };
  };
}
